export const BOOKMARK_ADD_REQUEST = 'BOOKMARK_ADD_REQUEST';
export const BOOKMARK_ADD_SUCCESS = 'BOOKMARK_ADD_SUCCESS';
export const BOOKMARK_ADD_FAIL = 'BOOKMARK_ADD_FAIL';

export const BOOKMARK_REMOVE_REQUEST = 'BOOKMARK_REMOVE_REQUEST';
export const BOOKMARK_REMOVE_SUCCESS = 'BOOKMARK_REMOVE_SUCCESS';
export const BOOKMARK_REMOVE_FAIL = 'BOOKMARK_REMOVE_FAIL';

export const BOOKMARK_LIST_REQUEST = 'BOOKMARK_LIST_REQUEST';
export const BOOKMARK_LIST_SUCCESS = 'BOOKMARK_LIST_SUCCESS';
export const BOOKMARK_LIST_FAIL = 'BOOKMARK_LIST_FAIL';
