export const SUBSCRIBE_REQUEST = 'SUBSCRIBE_REQUEST';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const SUBSCRIBE_FAIL = 'SUBSCRIBE_FAIL';
export const SUBSCRIBE_RESET = 'SUBSCRIBE_RESET';
export const PAYMENT_SAVE_METHOD = 'PAYMENT_SAVE_METHOD';