# Generated by Django 5.1.5 on 2025-03-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('premium', 'Premium'), ('free', 'Free')], default='free', max_length=10),
        ),
    ]
