# Generated by Django 5.1.5 on 2025-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='restricted',
            field=models.BooleanField(default=True),
        ),
    ]
