# Generated by Django 5.1.5 on 2025-03-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_movie_movie_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_file',
            new_name='video',
        ),
    ]
