# Generated by Django 5.1.5 on 2025-03-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
